// flow-typed signature: ad5ee295e73f04c118c961a1ea4ba986
// flow-typed version: <<STUB>>/annict_v^0.0.8/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'annict'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'annict' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'annict/browser/annict.min' {
  declare module.exports: any;
}

declare module 'annict/lib/annict' {
  declare module.exports: any;
}

declare module 'annict/lib/http-client' {
  declare module.exports: any;
}

declare module 'annict/lib/services/authorization-service' {
  declare module.exports: any;
}

declare module 'annict/lib/services/episodes-service' {
  declare module.exports: any;
}

declare module 'annict/lib/services/index' {
  declare module.exports: any;
}

declare module 'annict/lib/services/me-service' {
  declare module.exports: any;
}

declare module 'annict/lib/services/me/index' {
  declare module.exports: any;
}

declare module 'annict/lib/services/me/me-programs-service' {
  declare module.exports: any;
}

declare module 'annict/lib/services/me/me-records-service' {
  declare module.exports: any;
}

declare module 'annict/lib/services/me/me-statuses-service' {
  declare module.exports: any;
}

declare module 'annict/lib/services/me/me-works-service' {
  declare module.exports: any;
}

declare module 'annict/lib/services/records-service' {
  declare module.exports: any;
}

declare module 'annict/lib/services/works-service' {
  declare module.exports: any;
}

declare module 'annict/lib/string-literal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'annict/browser/annict.min.js' {
  declare module.exports: $Exports<'annict/browser/annict.min'>;
}
declare module 'annict/lib/annict.js' {
  declare module.exports: $Exports<'annict/lib/annict'>;
}
declare module 'annict/lib/http-client.js' {
  declare module.exports: $Exports<'annict/lib/http-client'>;
}
declare module 'annict/lib/services/authorization-service.js' {
  declare module.exports: $Exports<'annict/lib/services/authorization-service'>;
}
declare module 'annict/lib/services/episodes-service.js' {
  declare module.exports: $Exports<'annict/lib/services/episodes-service'>;
}
declare module 'annict/lib/services/index.js' {
  declare module.exports: $Exports<'annict/lib/services/index'>;
}
declare module 'annict/lib/services/me-service.js' {
  declare module.exports: $Exports<'annict/lib/services/me-service'>;
}
declare module 'annict/lib/services/me/index.js' {
  declare module.exports: $Exports<'annict/lib/services/me/index'>;
}
declare module 'annict/lib/services/me/me-programs-service.js' {
  declare module.exports: $Exports<'annict/lib/services/me/me-programs-service'>;
}
declare module 'annict/lib/services/me/me-records-service.js' {
  declare module.exports: $Exports<'annict/lib/services/me/me-records-service'>;
}
declare module 'annict/lib/services/me/me-statuses-service.js' {
  declare module.exports: $Exports<'annict/lib/services/me/me-statuses-service'>;
}
declare module 'annict/lib/services/me/me-works-service.js' {
  declare module.exports: $Exports<'annict/lib/services/me/me-works-service'>;
}
declare module 'annict/lib/services/records-service.js' {
  declare module.exports: $Exports<'annict/lib/services/records-service'>;
}
declare module 'annict/lib/services/works-service.js' {
  declare module.exports: $Exports<'annict/lib/services/works-service'>;
}
declare module 'annict/lib/string-literal.js' {
  declare module.exports: $Exports<'annict/lib/string-literal'>;
}
