// flow-typed signature: 9ce262346ba7fc2f5ba3ff2a3ef92e78
// flow-typed version: <<STUB>>/babel-preset-react-app_v^3.1.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-react-app/index' {
  declare module.exports: $Exports<'babel-preset-react-app'>;
}
declare module 'babel-preset-react-app/index.js' {
  declare module.exports: $Exports<'babel-preset-react-app'>;
}
