// flow-typed signature: 32fd4996f57ad411b917dc622c7d72dc
// flow-typed version: <<STUB>>/babel-plugin-s2s-variable-initializing_v^0.1.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-s2s-variable-initializing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-s2s-variable-initializing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-s2s-variable-initializing/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-s2s-variable-initializing/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-s2s-variable-initializing/lib/index'>;
}
