// flow-typed signature: d521f17ddc7bbe360c2ba7a5d095fcf0
// flow-typed version: <<STUB>>/onsenui_v^2.9.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'onsenui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'onsenui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'onsenui/css-components-src/gulpfile' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/app' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/app-page' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/category-page' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/component-page' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/components-page' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/notfound-page' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/pattern-page' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/patterns-page' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/platform-select' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/preview-component' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/components/theme-select' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/previewer-src/util' {
  declare module.exports: any;
}

declare module 'onsenui/css-components-src/stylelint.config' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/base/base-button' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/base/base-checkbox' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/base/base-dialog' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/base/base-element' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/base/base-input' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-action-sheet-button' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-action-sheet/animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-action-sheet/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-alert-dialog-button' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-alert-dialog/animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-alert-dialog/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-back-button' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-bottom-toolbar' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-button' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-card' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-carousel-item' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-carousel' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-checkbox' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-col' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-dialog/animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-dialog/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-fab' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-gesture-detector' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-icon' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-if' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-input' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-lazy-repeat' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-list-header' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-list-item' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-list-title' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-list' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-modal/animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-modal/fade-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-modal/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-modal/lift-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/ios-fade-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/ios-lift-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/ios-slide-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/ios-swipe-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/md-fade-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/md-lift-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/md-slide-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-navigator/none-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-page' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-popover/animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-popover/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-progress-bar' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-progress-circular' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-pull-hook' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-radio' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-range' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-ripple/animator-css' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-ripple/animator-js' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-ripple/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-row' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-search-input' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-segment' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-select' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-speed-dial-item' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-speed-dial' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-splitter-content' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-splitter-mask' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-splitter-side' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-splitter/animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-splitter/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-splitter/overlay-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-splitter/push-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-splitter/reveal-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-switch' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-tab' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-tabbar/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-template' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-toast/animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-toast/ascend-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-toast/fade-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-toast/fall-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-toast/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-toast/lift-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-toolbar-button' {
  declare module.exports: any;
}

declare module 'onsenui/esm/elements/ons-toolbar' {
  declare module.exports: any;
}

declare module 'onsenui/esm/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/action-sheet' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/animation-options-parser' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/animit' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/autostyle' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/base-animator' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/content-ready' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/doorlock' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/elements' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/gesture-detector' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/animator-factory' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/device-back-button-dispatcher' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/internal' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/lazy-repeat' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/modifier-util' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/swipe-reveal' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/swiper' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/internal/toast-queue' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/iphonex-patch' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/microevent' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/modifier' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/notification' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/orientation' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/page-attribute-expression' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/page-loader' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/platform' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/software-keyboard' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/styler' {
  declare module.exports: any;
}

declare module 'onsenui/esm/ons/util' {
  declare module.exports: any;
}

declare module 'onsenui/esm/polyfills/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/polyfills/MutationObserver@0.7.22/MutationObserver' {
  declare module.exports: any;
}

declare module 'onsenui/esm/polyfills/polyfill-switches' {
  declare module.exports: any;
}

declare module 'onsenui/esm/polyfills/setImmediate@1.0.2+mod/setImmediate' {
  declare module.exports: any;
}

declare module 'onsenui/esm/vendor/index' {
  declare module.exports: any;
}

declare module 'onsenui/esm/vendor/viewport' {
  declare module.exports: any;
}

declare module 'onsenui/js/angular-onsenui' {
  declare module.exports: any;
}

declare module 'onsenui/js/angular-onsenui.min' {
  declare module.exports: any;
}

declare module 'onsenui/js/onsenui' {
  declare module.exports: any;
}

declare module 'onsenui/js/onsenui.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'onsenui/css-components-src/gulpfile.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/gulpfile'>;
}
declare module 'onsenui/css-components-src/previewer-src/app.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/app'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/app-page.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/app-page'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/category-page.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/category-page'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/component-page.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/component-page'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/components-page.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/components-page'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/notfound-page.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/notfound-page'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/pattern-page.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/pattern-page'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/patterns-page.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/patterns-page'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/platform-select.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/platform-select'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/preview-component.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/preview-component'>;
}
declare module 'onsenui/css-components-src/previewer-src/components/theme-select.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/components/theme-select'>;
}
declare module 'onsenui/css-components-src/previewer-src/util.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/previewer-src/util'>;
}
declare module 'onsenui/css-components-src/stylelint.config.js' {
  declare module.exports: $Exports<'onsenui/css-components-src/stylelint.config'>;
}
declare module 'onsenui/esm/elements/base/base-button.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/base/base-button'>;
}
declare module 'onsenui/esm/elements/base/base-checkbox.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/base/base-checkbox'>;
}
declare module 'onsenui/esm/elements/base/base-dialog.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/base/base-dialog'>;
}
declare module 'onsenui/esm/elements/base/base-element.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/base/base-element'>;
}
declare module 'onsenui/esm/elements/base/base-input.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/base/base-input'>;
}
declare module 'onsenui/esm/elements/ons-action-sheet-button.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-action-sheet-button'>;
}
declare module 'onsenui/esm/elements/ons-action-sheet/animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-action-sheet/animator'>;
}
declare module 'onsenui/esm/elements/ons-action-sheet/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-action-sheet/index'>;
}
declare module 'onsenui/esm/elements/ons-alert-dialog-button.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-alert-dialog-button'>;
}
declare module 'onsenui/esm/elements/ons-alert-dialog/animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-alert-dialog/animator'>;
}
declare module 'onsenui/esm/elements/ons-alert-dialog/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-alert-dialog/index'>;
}
declare module 'onsenui/esm/elements/ons-back-button.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-back-button'>;
}
declare module 'onsenui/esm/elements/ons-bottom-toolbar.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-bottom-toolbar'>;
}
declare module 'onsenui/esm/elements/ons-button.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-button'>;
}
declare module 'onsenui/esm/elements/ons-card.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-card'>;
}
declare module 'onsenui/esm/elements/ons-carousel-item.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-carousel-item'>;
}
declare module 'onsenui/esm/elements/ons-carousel.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-carousel'>;
}
declare module 'onsenui/esm/elements/ons-checkbox.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-checkbox'>;
}
declare module 'onsenui/esm/elements/ons-col.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-col'>;
}
declare module 'onsenui/esm/elements/ons-dialog/animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-dialog/animator'>;
}
declare module 'onsenui/esm/elements/ons-dialog/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-dialog/index'>;
}
declare module 'onsenui/esm/elements/ons-fab.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-fab'>;
}
declare module 'onsenui/esm/elements/ons-gesture-detector.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-gesture-detector'>;
}
declare module 'onsenui/esm/elements/ons-icon.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-icon'>;
}
declare module 'onsenui/esm/elements/ons-if.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-if'>;
}
declare module 'onsenui/esm/elements/ons-input.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-input'>;
}
declare module 'onsenui/esm/elements/ons-lazy-repeat.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-lazy-repeat'>;
}
declare module 'onsenui/esm/elements/ons-list-header.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-list-header'>;
}
declare module 'onsenui/esm/elements/ons-list-item.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-list-item'>;
}
declare module 'onsenui/esm/elements/ons-list-title.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-list-title'>;
}
declare module 'onsenui/esm/elements/ons-list.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-list'>;
}
declare module 'onsenui/esm/elements/ons-modal/animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-modal/animator'>;
}
declare module 'onsenui/esm/elements/ons-modal/fade-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-modal/fade-animator'>;
}
declare module 'onsenui/esm/elements/ons-modal/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-modal/index'>;
}
declare module 'onsenui/esm/elements/ons-modal/lift-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-modal/lift-animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/index'>;
}
declare module 'onsenui/esm/elements/ons-navigator/ios-fade-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/ios-fade-animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/ios-lift-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/ios-lift-animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/ios-slide-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/ios-slide-animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/ios-swipe-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/ios-swipe-animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/md-fade-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/md-fade-animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/md-lift-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/md-lift-animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/md-slide-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/md-slide-animator'>;
}
declare module 'onsenui/esm/elements/ons-navigator/none-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-navigator/none-animator'>;
}
declare module 'onsenui/esm/elements/ons-page.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-page'>;
}
declare module 'onsenui/esm/elements/ons-popover/animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-popover/animator'>;
}
declare module 'onsenui/esm/elements/ons-popover/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-popover/index'>;
}
declare module 'onsenui/esm/elements/ons-progress-bar.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-progress-bar'>;
}
declare module 'onsenui/esm/elements/ons-progress-circular.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-progress-circular'>;
}
declare module 'onsenui/esm/elements/ons-pull-hook.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-pull-hook'>;
}
declare module 'onsenui/esm/elements/ons-radio.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-radio'>;
}
declare module 'onsenui/esm/elements/ons-range.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-range'>;
}
declare module 'onsenui/esm/elements/ons-ripple/animator-css.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-ripple/animator-css'>;
}
declare module 'onsenui/esm/elements/ons-ripple/animator-js.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-ripple/animator-js'>;
}
declare module 'onsenui/esm/elements/ons-ripple/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-ripple/index'>;
}
declare module 'onsenui/esm/elements/ons-row.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-row'>;
}
declare module 'onsenui/esm/elements/ons-search-input.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-search-input'>;
}
declare module 'onsenui/esm/elements/ons-segment.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-segment'>;
}
declare module 'onsenui/esm/elements/ons-select.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-select'>;
}
declare module 'onsenui/esm/elements/ons-speed-dial-item.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-speed-dial-item'>;
}
declare module 'onsenui/esm/elements/ons-speed-dial.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-speed-dial'>;
}
declare module 'onsenui/esm/elements/ons-splitter-content.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-splitter-content'>;
}
declare module 'onsenui/esm/elements/ons-splitter-mask.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-splitter-mask'>;
}
declare module 'onsenui/esm/elements/ons-splitter-side.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-splitter-side'>;
}
declare module 'onsenui/esm/elements/ons-splitter/animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-splitter/animator'>;
}
declare module 'onsenui/esm/elements/ons-splitter/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-splitter/index'>;
}
declare module 'onsenui/esm/elements/ons-splitter/overlay-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-splitter/overlay-animator'>;
}
declare module 'onsenui/esm/elements/ons-splitter/push-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-splitter/push-animator'>;
}
declare module 'onsenui/esm/elements/ons-splitter/reveal-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-splitter/reveal-animator'>;
}
declare module 'onsenui/esm/elements/ons-switch.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-switch'>;
}
declare module 'onsenui/esm/elements/ons-tab.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-tab'>;
}
declare module 'onsenui/esm/elements/ons-tabbar/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-tabbar/index'>;
}
declare module 'onsenui/esm/elements/ons-template.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-template'>;
}
declare module 'onsenui/esm/elements/ons-toast/animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-toast/animator'>;
}
declare module 'onsenui/esm/elements/ons-toast/ascend-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-toast/ascend-animator'>;
}
declare module 'onsenui/esm/elements/ons-toast/fade-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-toast/fade-animator'>;
}
declare module 'onsenui/esm/elements/ons-toast/fall-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-toast/fall-animator'>;
}
declare module 'onsenui/esm/elements/ons-toast/index.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-toast/index'>;
}
declare module 'onsenui/esm/elements/ons-toast/lift-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-toast/lift-animator'>;
}
declare module 'onsenui/esm/elements/ons-toolbar-button.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-toolbar-button'>;
}
declare module 'onsenui/esm/elements/ons-toolbar.js' {
  declare module.exports: $Exports<'onsenui/esm/elements/ons-toolbar'>;
}
declare module 'onsenui/esm/index.js' {
  declare module.exports: $Exports<'onsenui/esm/index'>;
}
declare module 'onsenui/esm/ons/action-sheet.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/action-sheet'>;
}
declare module 'onsenui/esm/ons/animation-options-parser.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/animation-options-parser'>;
}
declare module 'onsenui/esm/ons/animit.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/animit'>;
}
declare module 'onsenui/esm/ons/autostyle.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/autostyle'>;
}
declare module 'onsenui/esm/ons/base-animator.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/base-animator'>;
}
declare module 'onsenui/esm/ons/content-ready.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/content-ready'>;
}
declare module 'onsenui/esm/ons/doorlock.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/doorlock'>;
}
declare module 'onsenui/esm/ons/elements.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/elements'>;
}
declare module 'onsenui/esm/ons/gesture-detector.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/gesture-detector'>;
}
declare module 'onsenui/esm/ons/index.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/index'>;
}
declare module 'onsenui/esm/ons/internal/animator-factory.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/animator-factory'>;
}
declare module 'onsenui/esm/ons/internal/device-back-button-dispatcher.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/device-back-button-dispatcher'>;
}
declare module 'onsenui/esm/ons/internal/index.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/index'>;
}
declare module 'onsenui/esm/ons/internal/internal.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/internal'>;
}
declare module 'onsenui/esm/ons/internal/lazy-repeat.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/lazy-repeat'>;
}
declare module 'onsenui/esm/ons/internal/modifier-util.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/modifier-util'>;
}
declare module 'onsenui/esm/ons/internal/swipe-reveal.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/swipe-reveal'>;
}
declare module 'onsenui/esm/ons/internal/swiper.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/swiper'>;
}
declare module 'onsenui/esm/ons/internal/toast-queue.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/internal/toast-queue'>;
}
declare module 'onsenui/esm/ons/iphonex-patch.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/iphonex-patch'>;
}
declare module 'onsenui/esm/ons/microevent.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/microevent'>;
}
declare module 'onsenui/esm/ons/modifier.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/modifier'>;
}
declare module 'onsenui/esm/ons/notification.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/notification'>;
}
declare module 'onsenui/esm/ons/orientation.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/orientation'>;
}
declare module 'onsenui/esm/ons/page-attribute-expression.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/page-attribute-expression'>;
}
declare module 'onsenui/esm/ons/page-loader.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/page-loader'>;
}
declare module 'onsenui/esm/ons/platform.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/platform'>;
}
declare module 'onsenui/esm/ons/software-keyboard.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/software-keyboard'>;
}
declare module 'onsenui/esm/ons/styler.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/styler'>;
}
declare module 'onsenui/esm/ons/util.js' {
  declare module.exports: $Exports<'onsenui/esm/ons/util'>;
}
declare module 'onsenui/esm/polyfills/index.js' {
  declare module.exports: $Exports<'onsenui/esm/polyfills/index'>;
}
declare module 'onsenui/esm/polyfills/MutationObserver@0.7.22/MutationObserver.js' {
  declare module.exports: $Exports<'onsenui/esm/polyfills/MutationObserver@0.7.22/MutationObserver'>;
}
declare module 'onsenui/esm/polyfills/polyfill-switches.js' {
  declare module.exports: $Exports<'onsenui/esm/polyfills/polyfill-switches'>;
}
declare module 'onsenui/esm/polyfills/setImmediate@1.0.2+mod/setImmediate.js' {
  declare module.exports: $Exports<'onsenui/esm/polyfills/setImmediate@1.0.2+mod/setImmediate'>;
}
declare module 'onsenui/esm/vendor/index.js' {
  declare module.exports: $Exports<'onsenui/esm/vendor/index'>;
}
declare module 'onsenui/esm/vendor/viewport.js' {
  declare module.exports: $Exports<'onsenui/esm/vendor/viewport'>;
}
declare module 'onsenui/js/angular-onsenui.js' {
  declare module.exports: $Exports<'onsenui/js/angular-onsenui'>;
}
declare module 'onsenui/js/angular-onsenui.min.js' {
  declare module.exports: $Exports<'onsenui/js/angular-onsenui.min'>;
}
declare module 'onsenui/js/onsenui.js' {
  declare module.exports: $Exports<'onsenui/js/onsenui'>;
}
declare module 'onsenui/js/onsenui.min.js' {
  declare module.exports: $Exports<'onsenui/js/onsenui.min'>;
}
