// flow-typed signature: ea784e395a9684a2d1d172e685821985
// flow-typed version: <<STUB>>/react-onsenui_v^1.10.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onsenui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onsenui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-onsenui/dist/react-onsenui' {
  declare module.exports: any;
}

declare module 'react-onsenui/dist/react-onsenui.min' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/ActionSheet' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/ActionSheetButton' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/AlertDialog' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/AlertDialogButton' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/BackButton' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/BaseDialog' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/BaseInput' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/BasicComponent' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/BottomToolbar' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Button' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Card' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Carousel' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Checkbox' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Col' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Dialog' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Fab' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Icon' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Input' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/LazyList' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/List' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/ListHeader' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/ListItem' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/ListTitle' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Modal' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Navigator' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Page' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Popover' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/ProgressCircular' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/PullHook' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Radio' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Range' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Ripple' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/RouterNavigator' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Row' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/SearchInput' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Segment' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Select' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/SimpleWrapper' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/SpeedDial' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/SpeedDialItem' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Splitter' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/SplitterContent' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/SplitterSide' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Switch' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Tab' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Tabbar' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Toast' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Toolbar' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/ToolbarButton' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/components/Util' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/index.umd' {
  declare module.exports: any;
}

declare module 'react-onsenui/src/RouterUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-onsenui/dist/react-onsenui.js' {
  declare module.exports: $Exports<'react-onsenui/dist/react-onsenui'>;
}
declare module 'react-onsenui/dist/react-onsenui.min.js' {
  declare module.exports: $Exports<'react-onsenui/dist/react-onsenui.min'>;
}
declare module 'react-onsenui/src/components/ActionSheet.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/ActionSheet'>;
}
declare module 'react-onsenui/src/components/ActionSheetButton.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/ActionSheetButton'>;
}
declare module 'react-onsenui/src/components/AlertDialog.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/AlertDialog'>;
}
declare module 'react-onsenui/src/components/AlertDialogButton.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/AlertDialogButton'>;
}
declare module 'react-onsenui/src/components/BackButton.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/BackButton'>;
}
declare module 'react-onsenui/src/components/BaseDialog.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/BaseDialog'>;
}
declare module 'react-onsenui/src/components/BaseInput.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/BaseInput'>;
}
declare module 'react-onsenui/src/components/BasicComponent.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/BasicComponent'>;
}
declare module 'react-onsenui/src/components/BottomToolbar.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/BottomToolbar'>;
}
declare module 'react-onsenui/src/components/Button.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Button'>;
}
declare module 'react-onsenui/src/components/Card.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Card'>;
}
declare module 'react-onsenui/src/components/Carousel.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Carousel'>;
}
declare module 'react-onsenui/src/components/CarouselItem.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/CarouselItem'>;
}
declare module 'react-onsenui/src/components/Checkbox.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Checkbox'>;
}
declare module 'react-onsenui/src/components/Col.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Col'>;
}
declare module 'react-onsenui/src/components/Dialog.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Dialog'>;
}
declare module 'react-onsenui/src/components/Fab.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Fab'>;
}
declare module 'react-onsenui/src/components/Icon.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Icon'>;
}
declare module 'react-onsenui/src/components/Input.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Input'>;
}
declare module 'react-onsenui/src/components/LazyList.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/LazyList'>;
}
declare module 'react-onsenui/src/components/List.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/List'>;
}
declare module 'react-onsenui/src/components/ListHeader.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/ListHeader'>;
}
declare module 'react-onsenui/src/components/ListItem.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/ListItem'>;
}
declare module 'react-onsenui/src/components/ListTitle.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/ListTitle'>;
}
declare module 'react-onsenui/src/components/Modal.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Modal'>;
}
declare module 'react-onsenui/src/components/Navigator.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Navigator'>;
}
declare module 'react-onsenui/src/components/Page.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Page'>;
}
declare module 'react-onsenui/src/components/Popover.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Popover'>;
}
declare module 'react-onsenui/src/components/ProgressBar.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/ProgressBar'>;
}
declare module 'react-onsenui/src/components/ProgressCircular.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/ProgressCircular'>;
}
declare module 'react-onsenui/src/components/PullHook.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/PullHook'>;
}
declare module 'react-onsenui/src/components/Radio.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Radio'>;
}
declare module 'react-onsenui/src/components/Range.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Range'>;
}
declare module 'react-onsenui/src/components/Ripple.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Ripple'>;
}
declare module 'react-onsenui/src/components/RouterNavigator.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/RouterNavigator'>;
}
declare module 'react-onsenui/src/components/Row.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Row'>;
}
declare module 'react-onsenui/src/components/SearchInput.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/SearchInput'>;
}
declare module 'react-onsenui/src/components/Segment.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Segment'>;
}
declare module 'react-onsenui/src/components/Select.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Select'>;
}
declare module 'react-onsenui/src/components/SimpleWrapper.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/SimpleWrapper'>;
}
declare module 'react-onsenui/src/components/SpeedDial.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/SpeedDial'>;
}
declare module 'react-onsenui/src/components/SpeedDialItem.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/SpeedDialItem'>;
}
declare module 'react-onsenui/src/components/Splitter.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Splitter'>;
}
declare module 'react-onsenui/src/components/SplitterContent.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/SplitterContent'>;
}
declare module 'react-onsenui/src/components/SplitterSide.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/SplitterSide'>;
}
declare module 'react-onsenui/src/components/Switch.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Switch'>;
}
declare module 'react-onsenui/src/components/Tab.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Tab'>;
}
declare module 'react-onsenui/src/components/Tabbar.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Tabbar'>;
}
declare module 'react-onsenui/src/components/Toast.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Toast'>;
}
declare module 'react-onsenui/src/components/Toolbar.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/Toolbar'>;
}
declare module 'react-onsenui/src/components/ToolbarButton.jsx' {
  declare module.exports: $Exports<'react-onsenui/src/components/ToolbarButton'>;
}
declare module 'react-onsenui/src/components/Util.js' {
  declare module.exports: $Exports<'react-onsenui/src/components/Util'>;
}
declare module 'react-onsenui/src/index.umd.js' {
  declare module.exports: $Exports<'react-onsenui/src/index.umd'>;
}
declare module 'react-onsenui/src/RouterUtil.js' {
  declare module.exports: $Exports<'react-onsenui/src/RouterUtil'>;
}
